spring:
  profiles.active: local

---
spring:
  profiles: local
  datasource:
     jdbc-url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useAffectedRows=true
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
     initial-size: 3
     max-active: 20
     min-idle: 2
     validation-query: SELECT 1

server.port: 8081

